import type { CulturalLocation } from './types';

/**
 * Seed data for cultural locations across India
 * MVP: 50 locations (major cities + heritage sites)
 */
export const culturalLocationsSeedData: CulturalLocation[] = [
    // ============================================
    // MAJOR CITIES (20 locations)
    // ============================================

    // North India
    {
        id: 'delhi',
        name: 'Delhi',
        nameHindi: 'दिल्ली',
        type: 'city',
        coordinates: [28.6139, 77.2090],
        story: 'The capital city of India, Delhi is a vibrant tapestry of history and modernity. From the majestic Red Fort to the serene Lotus Temple, Delhi embodies the Ganga-Jamuni tehzeeb - a confluence of Hindu and Muslim cultures that has shaped North Indian civilization for centuries.',
        category: 'heritage',
        images: ['/images/locations/delhi.jpg'],
        state: 'Delhi',
        minZoom: 5,
        importance: 1,
        tags: ['capital', 'mughal', 'heritage', 'monuments'],
    },
    {
        id: 'varanasi',
        name: 'Varanasi',
        nameHindi: 'वाराणसी',
        type: 'city',
        coordinates: [25.3176, 82.9739],
        story: 'One of the oldest continuously inhabited cities in the world, Varanasi is the spiritual heart of India. The ghats along the Ganges River witness thousands of devotees performing ancient rituals at dawn, while the narrow lanes echo with temple bells and classical music.',
        category: 'tradition',
        images: ['/images/locations/varanasi.jpg'],
        state: 'Uttar Pradesh',
        minZoom: 6,
        importance: 1,
        tags: ['spiritual', 'ganges', 'ancient', 'pilgrimage'],
    },
    {
        id: 'jaipur',
        name: 'Jaipur',
        nameHindi: 'जयपुर',
        type: 'city',
        coordinates: [26.9124, 75.7873],
        story: 'The Pink City of India, Jaipur is a testament to Rajputana grandeur. Its magnificent forts, palaces, and havelis showcase the finest Rajasthani architecture, while its bazaars overflow with traditional handicrafts, textiles, and jewelry.',
        category: 'heritage',
        images: ['/images/locations/jaipur.jpg'],
        state: 'Rajasthan',
        minZoom: 6,
        importance: 1,
        tags: ['pink-city', 'rajput', 'forts', 'palaces'],
    },
    {
        id: 'amritsar',
        name: 'Amritsar',
        nameHindi: 'अमृतसर',
        type: 'city',
        coordinates: [31.6340, 74.8723],
        story: 'Home to the Golden Temple, Amritsar is the spiritual and cultural center of Sikhism. The city resonates with devotional music, serves thousands of free meals daily at the langar, and stands as a symbol of equality, service, and faith.',
        category: 'tradition',
        images: ['/images/locations/amritsar.jpg'],
        state: 'Punjab',
        minZoom: 6,
        importance: 1,
        tags: ['golden-temple', 'sikh', 'langar', 'spiritual'],
    },

    // West India
    {
        id: 'mumbai',
        name: 'Mumbai',
        nameHindi: 'मुंबई',
        type: 'city',
        coordinates: [19.0760, 72.8777],
        story: 'The City of Dreams, Mumbai is India\'s financial capital and the heart of Bollywood. From the iconic Gateway of India to the bustling streets of Dharavi, Mumbai represents the aspirations and diversity of modern India.',
        category: 'art',
        images: ['/images/locations/mumbai.jpg'],
        state: 'Maharashtra',
        minZoom: 5,
        importance: 1,
        tags: ['bollywood', 'financial', 'gateway', 'cosmopolitan'],
    },
    {
        id: 'ahmedabad',
        name: 'Ahmedabad',
        nameHindi: 'अहमदाबाद',
        type: 'city',
        coordinates: [23.0225, 72.5714],
        story: 'A UNESCO World Heritage City, Ahmedabad blends medieval Islamic architecture with vibrant Gujarati culture. The city is famous for its textile heritage, intricate pols (traditional housing clusters), and the Sabarmati Ashram where Gandhi led India\'s freedom movement.',
        category: 'heritage',
        images: ['/images/locations/ahmedabad.jpg'],
        state: 'Gujarat',
        minZoom: 6,
        importance: 1,
        tags: ['unesco', 'gandhi', 'textiles', 'heritage'],
    },

    // South India
    {
        id: 'chennai',
        name: 'Chennai',
        nameHindi: 'चेन्नई',
        type: 'city',
        coordinates: [13.0827, 80.2707],
        story: 'The cultural capital of South India, Chennai is renowned for its classical music, dance, and temple architecture. The city\'s Carnatic music season attracts artists from around the world, while its ancient temples showcase Dravidian architectural brilliance.',
        category: 'music',
        images: ['/images/locations/chennai.jpg'],
        state: 'Tamil Nadu',
        minZoom: 5,
        importance: 1,
        tags: ['carnatic', 'classical', 'temples', 'dravidian'],
    },
    {
        id: 'bangalore',
        name: 'Bangalore',
        nameHindi: 'बेंगलुरु',
        type: 'city',
        coordinates: [12.9716, 77.5946],
        story: 'The Garden City and IT hub of India, Bangalore beautifully balances its heritage as a center of Kannada culture with its modern identity as a tech metropolis. The city\'s parks, palaces, and vibrant arts scene make it unique.',
        category: 'art',
        images: ['/images/locations/bangalore.jpg'],
        state: 'Karnataka',
        minZoom: 5,
        importance: 1,
        tags: ['garden-city', 'tech', 'kannada', 'modern'],
    },
    {
        id: 'kochi',
        name: 'Kochi',
        nameHindi: 'कोच्चि',
        type: 'city',
        coordinates: [9.9312, 76.2673],
        story: 'The Queen of the Arabian Sea, Kochi has been a melting pot of cultures for centuries. Chinese fishing nets, Dutch palaces, Portuguese churches, and Jewish synagogues tell the story of this historic port city\'s cosmopolitan heritage.',
        category: 'heritage',
        images: ['/images/locations/kochi.jpg'],
        state: 'Kerala',
        minZoom: 6,
        importance: 1,
        tags: ['port', 'spices', 'cosmopolitan', 'backwaters'],
    },
    {
        id: 'hyderabad',
        name: 'Hyderabad',
        nameHindi: 'हैदराबाद',
        type: 'city',
        coordinates: [17.3850, 78.4867],
        story: 'The City of Pearls and Nizams, Hyderabad is famous for its rich history, biryani, and the iconic Charminar. The city beautifully preserves its Nizami heritage while embracing modernity as a major IT hub.',
        category: 'food',
        images: ['/images/locations/hyderabad.jpg'],
        state: 'Telangana',
        minZoom: 5,
        importance: 1,
        tags: ['nizami', 'biryani', 'pearls', 'charminar'],
    },

    // East India
    {
        id: 'kolkata',
        name: 'Kolkata',
        nameHindi: 'कोलकाता',
        type: 'city',
        coordinates: [22.5726, 88.3639],
        story: 'The City of Joy and cultural capital of Eastern India, Kolkata is the birthplace of the Bengali Renaissance. From Rabindranath Tagore\'s poetry to Durga Puja celebrations, the city breathes art, literature, and intellectual fervor.',
        category: 'art',
        images: ['/images/locations/kolkata.jpg'],
        state: 'West Bengal',
        minZoom: 5,
        importance: 1,
        tags: ['bengali', 'renaissance', 'durga-puja', 'literature'],
    },
    {
        id: 'bhubaneswar',
        name: 'Bhubaneswar',
        nameHindi: 'भुवनेश्वर',
        type: 'city',
        coordinates: [20.2961, 85.8245],
        story: 'The Temple City of India, Bhubaneswar boasts over 500 ancient temples showcasing Kalinga architecture. The city is also the gateway to the famous Konark Sun Temple and Puri Jagannath Temple.',
        category: 'heritage',
        images: ['/images/locations/bhubaneswar.jpg'],
        state: 'Odisha',
        minZoom: 6,
        importance: 2,
        tags: ['temples', 'kalinga', 'architecture', 'ancient'],
    },

    // Northeast India
    {
        id: 'guwahati',
        name: 'Guwahati',
        nameHindi: 'गुवाहाटी',
        type: 'city',
        coordinates: [26.1445, 91.7362],
        story: 'The Gateway to Northeast India, Guwahati sits on the banks of the mighty Brahmaputra River. The city is famous for the Kamakhya Temple and serves as the cultural hub of Assamese civilization.',
        category: 'tradition',
        images: ['/images/locations/guwahati.jpg'],
        state: 'Assam',
        minZoom: 6,
        importance: 2,
        tags: ['brahmaputra', 'kamakhya', 'assamese', 'northeast'],
    },

    // ============================================
    // HERITAGE SITES (30 locations)
    // ============================================

    // UNESCO World Heritage Sites
    {
        id: 'taj-mahal',
        name: 'Taj Mahal',
        nameHindi: 'ताज महल',
        type: 'heritage-site',
        coordinates: [27.1751, 78.0421],
        story: 'An eternal symbol of love, the Taj Mahal is one of the Seven Wonders of the World. Built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal, this white marble mausoleum is a masterpiece of Mughal architecture.',
        category: 'heritage',
        images: ['/images/locations/taj-mahal.jpg'],
        state: 'Uttar Pradesh',
        minZoom: 7,
        importance: 1,
        tags: ['unesco', 'wonder', 'mughal', 'monument'],
    },
    {
        id: 'hampi',
        name: 'Hampi',
        nameHindi: 'हम्पी',
        type: 'heritage-site',
        coordinates: [15.3350, 76.4600],
        story: 'The ruins of Hampi transport you to the glorious Vijayanagara Empire. Massive boulder-strewn landscapes dotted with magnificent temples, royal complexes, and ancient bazaars make Hampi a UNESCO World Heritage Site and a photographer\'s paradise.',
        category: 'heritage',
        images: ['/images/locations/hampi.jpg'],
        state: 'Karnataka',
        minZoom: 7,
        importance: 1,
        tags: ['unesco', 'vijayanagara', 'ruins', 'temples'],
    },
    {
        id: 'khajuraho',
        name: 'Khajuraho',
        nameHindi: 'खजुराहो',
        type: 'heritage-site',
        coordinates: [24.8318, 79.9199],
        story: 'Famous for its stunning temple sculptures, Khajuraho represents the pinnacle of medieval Indian art. The intricate carvings depicting various aspects of life, including the celebrated erotic sculptures, showcase the Chandela dynasty\'s artistic excellence.',
        category: 'art',
        images: ['/images/locations/khajuraho.jpg'],
        state: 'Madhya Pradesh',
        minZoom: 7,
        importance: 1,
        tags: ['unesco', 'temples', 'sculptures', 'chandela'],
    },
    {
        id: 'ajanta-caves',
        name: 'Ajanta Caves',
        nameHindi: 'अजंता गुफाएं',
        type: 'heritage-site',
        coordinates: [20.5519, 75.7033],
        story: 'The Ajanta Caves are ancient Buddhist rock-cut monuments dating back to the 2nd century BCE. The exquisite paintings and sculptures depicting the life of Buddha are considered masterpieces of Buddhist religious art.',
        category: 'art',
        images: ['/images/locations/ajanta.jpg'],
        state: 'Maharashtra',
        minZoom: 7,
        importance: 1,
        tags: ['unesco', 'buddhist', 'caves', 'paintings'],
    },
    {
        id: 'ellora-caves',
        name: 'Ellora Caves',
        nameHindi: 'एलोरा गुफाएं',
        type: 'heritage-site',
        coordinates: [20.0269, 75.1791],
        story: 'Ellora showcases the epitome of Indian rock-cut architecture with 34 monasteries and temples carved into the basalt cliffs. The Kailasa temple, carved from a single rock, is an engineering marvel representing Hindu, Buddhist, and Jain harmony.',
        category: 'heritage',
        images: ['/images/locations/ellora.jpg'],
        state: 'Maharashtra',
        minZoom: 7,
        importance: 1,
        tags: ['unesco', 'rock-cut', 'kailasa', 'caves'],
    },
    {
        id: 'konark-sun-temple',
        name: 'Konark Sun Temple',
        nameHindi: 'कोणार्क सूर्य मंदिर',
        type: 'heritage-site',
        coordinates: [19.8876, 86.0945],
        story: 'Designed as a colossal chariot of the Sun God Surya, the Konark Sun Temple is a 13th-century architectural marvel. Its intricate stone carvings and erotic sculptures represent the zenith of Kalinga architecture.',
        category: 'heritage',
        images: ['/images/locations/konark.jpg'],
        state: 'Odisha',
        minZoom: 7,
        importance: 1,
        tags: ['unesco', 'sun-temple', 'kalinga', 'architecture'],
    },
    {
        id: 'mahabalipuram',
        name: 'Mahabalipuram',
        nameHindi: 'महाबलीपुरम',
        type: 'heritage-site',
        coordinates: [12.6269, 80.1932],
        story: 'This ancient port city of the Pallava dynasty features magnificent rock-cut temples and sculptures. The Shore Temple, Pancha Rathas, and the massive Descent of the Ganges relief are UNESCO-recognized masterpieces.',
        category: 'heritage',
        images: ['/images/locations/mahabalipuram.jpg'],
        state: 'Tamil Nadu',
        minZoom: 7,
        importance: 1,
        tags: ['unesco', 'pallava', 'shore-temple', 'rock-cut'],
    },
    {
        id: 'sanchi-stupa',
        name: 'Sanchi Stupa',
        nameHindi: 'सांची स्तूप',
        type: 'heritage-site',
        coordinates: [23.4795, 77.7397],
        story: 'The Great Stupa at Sanchi is one of the oldest stone structures in India, commissioned by Emperor Ashoka in the 3rd century BCE. It represents the architectural and spiritual essence of early Buddhism.',
        category: 'heritage',
        images: ['/images/locations/sanchi.jpg'],
        state: 'Madhya Pradesh',
        minZoom: 7,
        importance: 2,
        tags: ['unesco', 'buddhist', 'ashoka', 'stupa'],
    },
    {
        id: 'fatehpur-sikri',
        name: 'Fatehpur Sikri',
        nameHindi: 'फतेहपुर सीकरी',
        type: 'heritage-site',
        coordinates: [27.0945, 77.6661],
        story: 'Built by Emperor Akbar, Fatehpur Sikri served as the Mughal capital for only 14 years but remains a stunning example of Mughal architecture. The Buland Darwaza and Panch Mahal are architectural highlights.',
        category: 'heritage',
        images: ['/images/locations/fatehpur-sikri.jpg'],
        state: 'Uttar Pradesh',
        minZoom: 7,
        importance: 2,
        tags: ['unesco', 'mughal', 'akbar', 'architecture'],
    },
    {
        id: 'qutub-minar',
        name: 'Qutub Minar',
        nameHindi: 'कुतुब मीनार',
        type: 'heritage-site',
        coordinates: [28.5244, 77.1855],
        story: 'The tallest brick minaret in the world, Qutub Minar stands as a symbol of Delhi\'s rich Islamic heritage. Built in the 12th century, the complex includes the mysterious Iron Pillar that has resisted rust for over 1,600 years.',
        category: 'heritage',
        images: ['/images/locations/qutub-minar.jpg'],
        state: 'Delhi',
        minZoom: 7,
        importance: 2,
        tags: ['unesco', 'minaret', 'delhi-sultanate', 'iron-pillar'],
    },

    // Famous Temples & Spiritual Sites
    {
        id: 'golden-temple',
        name: 'Golden Temple',
        nameHindi: 'स्वर्ण मंदिर',
        type: 'heritage-site',
        coordinates: [31.6200, 74.8765],
        story: 'Harmandir Sahib, the Golden Temple, is the holiest shrine of Sikhism. Its golden dome reflects in the sacred pool (Amrit Sarovar), creating a mesmerizing sight. The temple welcomes people of all faiths and serves free meals to over 100,000 visitors daily.',
        category: 'tradition',
        images: ['/images/locations/golden-temple.jpg'],
        state: 'Punjab',
        minZoom: 8,
        importance: 1,
        tags: ['sikh', 'gurdwara', 'amritsar', 'langar'],
    },
    {
        id: 'meenakshi-temple',
        name: 'Meenakshi Temple',
        nameHindi: 'मीनाक्षी मंदिर',
        type: 'heritage-site',
        coordinates: [9.9195, 78.1193],
        story: 'The Meenakshi Amman Temple in Madurai is a stunning example of Dravidian architecture with its towering gopurams covered in thousands of colorful sculptures. Dedicated to Goddess Meenakshi and Lord Sundareswarar, it\'s a living center of Tamil culture.',
        category: 'heritage',
        images: ['/images/locations/meenakshi.jpg'],
        state: 'Tamil Nadu',
        minZoom: 8,
        importance: 1,
        tags: ['dravidian', 'gopuram', 'madurai', 'temple'],
    },
    {
        id: 'tirupati',
        name: 'Tirupati Balaji',
        nameHindi: 'तिरुपति बालाजी',
        type: 'heritage-site',
        coordinates: [13.6833, 79.3472],
        story: 'The Tirumala Venkateswara Temple is the world\'s most visited pilgrimage site, receiving millions of devotees annually. Perched atop the seven hills of Tirumala, it\'s dedicated to Lord Venkateswara, an incarnation of Vishnu.',
        category: 'tradition',
        images: ['/images/locations/tirupati.jpg'],
        state: 'Andhra Pradesh',
        minZoom: 8,
        importance: 1,
        tags: ['pilgrimage', 'vishnu', 'tirumala', 'temple'],
    },
    {
        id: 'jagannath-puri',
        name: 'Jagannath Temple',
        nameHindi: 'जगन्नाथ मंदिर',
        type: 'heritage-site',
        coordinates: [19.8135, 85.8312],
        story: 'The Jagannath Temple in Puri is one of the Char Dham pilgrimage sites. Famous for the annual Rath Yatra where massive chariots carry the deities through the streets, it\'s a center of Odia culture and devotion.',
        category: 'festival',
        images: ['/images/locations/puri.jpg'],
        state: 'Odisha',
        minZoom: 8,
        importance: 1,
        tags: ['char-dham', 'rath-yatra', 'puri', 'temple'],
    },
    {
        id: 'somnath-temple',
        name: 'Somnath Temple',
        nameHindi: 'सोमनाथ मंदिर',
        type: 'heritage-site',
        coordinates: [20.8880, 70.4013],
        story: 'One of the twelve Jyotirlinga shrines of Lord Shiva, Somnath Temple has been destroyed and rebuilt multiple times throughout history. Standing majestically by the Arabian Sea, it symbolizes the resilience of faith.',
        category: 'tradition',
        images: ['/images/locations/somnath.jpg'],
        state: 'Gujarat',
        minZoom: 8,
        importance: 2,
        tags: ['jyotirlinga', 'shiva', 'arabian-sea', 'temple'],
    },

    // Forts & Palaces
    {
        id: 'red-fort',
        name: 'Red Fort',
        nameHindi: 'लाल किला',
        type: 'heritage-site',
        coordinates: [28.6562, 77.2410],
        story: 'The Red Fort served as the main residence of Mughal emperors for nearly 200 years. Its massive red sandstone walls enclose palaces, gardens, and the famous Diwan-i-Khas where the Peacock Throne once stood.',
        category: 'heritage',
        images: ['/images/locations/red-fort.jpg'],
        state: 'Delhi',
        minZoom: 8,
        importance: 1,
        tags: ['unesco', 'mughal', 'fort', 'independence'],
    },
    {
        id: 'amber-fort',
        name: 'Amber Fort',
        nameHindi: 'आमेर किला',
        type: 'heritage-site',
        coordinates: [26.9855, 75.8513],
        story: 'Perched on a hilltop overlooking Maota Lake, Amber Fort is a magnificent blend of Hindu and Mughal architecture. The Sheesh Mahal (Mirror Palace) with its intricate mirror work is particularly famous.',
        category: 'heritage',
        images: ['/images/locations/amber-fort.jpg'],
        state: 'Rajasthan',
        minZoom: 8,
        importance: 1,
        tags: ['rajput', 'fort', 'sheesh-mahal', 'jaipur'],
    },
    {
        id: 'mysore-palace',
        name: 'Mysore Palace',
        nameHindi: 'मैसूर पैलेस',
        type: 'heritage-site',
        coordinates: [12.3051, 76.6551],
        story: 'The official residence of the Wadiyar dynasty, Mysore Palace is an Indo-Saracenic architectural marvel. During Dussehra, the palace is illuminated with nearly 100,000 lights, creating a magical spectacle.',
        category: 'heritage',
        images: ['/images/locations/mysore-palace.jpg'],
        state: 'Karnataka',
        minZoom: 8,
        importance: 1,
        tags: ['palace', 'wadiyar', 'dussehra', 'indo-saracenic'],
    },
    {
        id: 'mehrangarh-fort',
        name: 'Mehrangarh Fort',
        nameHindi: 'मेहरानगढ़ किला',
        type: 'heritage-site',
        coordinates: [26.2985, 73.0190],
        story: 'Rising 400 feet above Jodhpur, Mehrangarh is one of India\'s largest forts. Its museums house an exquisite collection of palanquins, paintings, and royal artifacts, while its ramparts offer breathtaking views of the Blue City.',
        category: 'heritage',
        images: ['/images/locations/mehrangarh.jpg'],
        state: 'Rajasthan',
        minZoom: 8,
        importance: 2,
        tags: ['fort', 'jodhpur', 'rajput', 'blue-city'],
    },

    // Cultural Villages & Craft Centers
    {
        id: 'raghurajpur',
        name: 'Raghurajpur',
        nameHindi: 'रघुराजपुर',
        type: 'village',
        coordinates: [19.8167, 85.8833],
        story: 'India\'s first heritage crafts village, Raghurajpur is home to master Pattachitra painters and Gotipua dancers. Every house in this village is adorned with traditional murals, making it a living museum of Odia art.',
        category: 'art',
        images: ['/images/locations/raghurajpur.jpg'],
        state: 'Odisha',
        minZoom: 10,
        importance: 2,
        tags: ['pattachitra', 'crafts', 'village', 'heritage'],
    },
    {
        id: 'pochampally',
        name: 'Pochampally',
        nameHindi: 'पोचमपल्ली',
        type: 'village',
        coordinates: [17.3500, 78.7500],
        story: 'Known as the Silk City of India, Pochampally is famous for its ikat weaving technique. The village has received a Geographical Indication tag for its distinctive Pochampally sarees and fabrics.',
        category: 'craft',
        images: ['/images/locations/pochampally.jpg'],
        state: 'Telangana',
        minZoom: 10,
        importance: 2,
        tags: ['ikat', 'silk', 'weaving', 'textiles'],
    },
    {
        id: 'kutch-villages',
        name: 'Kutch Villages',
        nameHindi: 'कच्छ गांव',
        type: 'village',
        coordinates: [23.7337, 69.8597],
        story: 'The villages of Kutch are renowned for their vibrant handicrafts including bandhani, embroidery, and mirror work. The Rann of Kutch provides a stunning white desert backdrop to this rich cultural tapestry.',
        category: 'craft',
        images: ['/images/locations/kutch.jpg'],
        state: 'Gujarat',
        minZoom: 9,
        importance: 2,
        tags: ['handicrafts', 'rann', 'embroidery', 'desert'],
    },

    // Festival Locations
    {
        id: 'pushkar',
        name: 'Pushkar',
        nameHindi: 'पुष्कर',
        type: 'town',
        coordinates: [26.4899, 74.5511],
        story: 'Home to the world-famous Pushkar Camel Fair and one of the few Brahma temples in the world, Pushkar is a sacred town surrounding a holy lake. The annual fair transforms the desert into a vibrant carnival of culture.',
        category: 'festival',
        images: ['/images/locations/pushkar.jpg'],
        state: 'Rajasthan',
        minZoom: 9,
        importance: 2,
        tags: ['camel-fair', 'brahma-temple', 'sacred-lake', 'festival'],
    },
    {
        id: 'haridwar',
        name: 'Haridwar',
        nameHindi: 'हरिद्वार',
        type: 'city',
        coordinates: [29.9457, 78.1642],
        story: 'One of the seven holiest places in Hinduism, Haridwar is where the Ganges leaves the Himalayas. The evening Ganga Aarti at Har Ki Pauri is a spectacular display of devotion, with thousands of lamps floating on the sacred river.',
        category: 'tradition',
        images: ['/images/locations/haridwar.jpg'],
        state: 'Uttarakhand',
        minZoom: 7,
        importance: 1,
        tags: ['ganges', 'kumbh-mela', 'pilgrimage', 'aarti'],
    },
    {
        id: 'madurai',
        name: 'Madurai',
        nameHindi: 'मदुरै',
        type: 'city',
        coordinates: [9.9252, 78.1198],
        story: 'One of the oldest continuously inhabited cities in the world, Madurai is built around the magnificent Meenakshi Temple. The city is a center of Tamil culture, literature, and the ancient Sangam tradition.',
        category: 'heritage',
        images: ['/images/locations/madurai.jpg'],
        state: 'Tamil Nadu',
        minZoom: 7,
        importance: 1,
        tags: ['ancient', 'tamil', 'meenakshi', 'sangam'],
    },

    // Music & Dance Centers
    {
        id: 'thanjavur',
        name: 'Thanjavur',
        nameHindi: 'तंजावुर',
        type: 'city',
        coordinates: [10.7870, 79.1378],
        story: 'The cultural capital of Tamil Nadu, Thanjavur is famous for the Brihadeeswarar Temple, Tanjore paintings, and as the birthplace of Bharatanatyam dance. The city has been a center of South Indian art and music for over a millennium.',
        category: 'art',
        images: ['/images/locations/thanjavur.jpg'],
        state: 'Tamil Nadu',
        minZoom: 8,
        importance: 2,
        tags: ['bharatanatyam', 'tanjore-paintings', 'chola', 'art'],
    },
    {
        id: 'udaipur',
        name: 'Udaipur',
        nameHindi: 'उदयपुर',
        type: 'city',
        coordinates: [24.5854, 73.7125],
        story: 'The City of Lakes, Udaipur is a romantic destination with stunning palaces, lakes, and gardens. The City Palace complex and Lake Pichola create a fairy-tale setting that has inspired countless artists and filmmakers.',
        category: 'heritage',
        images: ['/images/locations/udaipur.jpg'],
        state: 'Rajasthan',
        minZoom: 7,
        importance: 1,
        tags: ['lakes', 'palaces', 'romantic', 'mewar'],
    },
    {
        id: 'rishikesh',
        name: 'Rishikesh',
        nameHindi: 'ऋषिकेश',
        type: 'city',
        coordinates: [30.0869, 78.2676],
        story: 'The Yoga Capital of the World, Rishikesh sits in the Himalayan foothills where the Ganges flows. The city is dotted with ashrams, temples, and the iconic Laxman Jhula suspension bridge, attracting spiritual seekers from around the globe.',
        category: 'tradition',
        images: ['/images/locations/rishikesh.jpg'],
        state: 'Uttarakhand',
        minZoom: 8,
        importance: 1,
        tags: ['yoga', 'ashrams', 'ganges', 'spiritual'],
    },
];
