/**
 * Cultural Items Seed Data for MaatiMap
 * Sample cultural items across India for testing the map feature
 */

import type { CulturalItem } from './types';

export const culturalItemsSeedData: Omit<CulturalItem, 'id'>[] = [
    // North India
    {
        title: 'Taj Mahal',
        summary: 'Iconic white marble mausoleum and UNESCO World Heritage Site',
        category: 'heritage-sites',
        state: 'Uttar Pradesh',
        region: 'North',
        latitude: 27.1751,
        longitude: 78.0421,
        imageUrl: 'https://i.postimg.cc/VkGJxHyG/taj-mahal.jpg',
        tags: ['architecture', 'unesco', 'monument'],
        description: 'The Taj Mahal is an ivory-white marble mausoleum on the right bank of the river Yamuna in Agra. Built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal.',
    },
    {
        title: 'Golden Temple',
        summary: 'Holiest Gurdwara of Sikhism with stunning golden architecture',
        category: 'heritage-sites',
        state: 'Punjab',
        region: 'North',
        latitude: 31.6200,
        longitude: 74.8765,
        imageUrl: 'https://i.postimg.cc/Y0qvKmYy/golden-temple.jpg',
        tags: ['sikh', 'temple', 'architecture'],
        description: 'Harmandir Sahib, also known as the Golden Temple, is a gurdwara located in Amritsar. It is the holiest Gurdwara and the most important pilgrimage site of Sikhism.',
    },
    {
        title: 'Holi Festival',
        summary: 'Festival of colors celebrating the arrival of spring',
        category: 'festivals',
        state: 'Uttar Pradesh',
        region: 'North',
        latitude: 27.4924,
        longitude: 77.6737,
        imageUrl: 'https://i.postimg.cc/nrGxJqwZ/holi.jpg',
        tags: ['festival', 'spring', 'colors'],
        description: 'Holi is a popular ancient Hindu festival celebrating the arrival of spring, love, and new life. Known as the "Festival of Colors".',
    },

    // South India
    {
        title: 'Kathakali Dance',
        summary: 'Classical Indian dance-drama from Kerala with elaborate costumes',
        category: 'art',
        state: 'Kerala',
        region: 'South',
        latitude: 10.8505,
        longitude: 76.2711,
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/kathakali.jpg',
        tags: ['dance', 'classical', 'performance'],
        description: 'Kathakali is a major form of classical Indian dance from Kerala. It is a story play genre of art, distinguished by its elaborate costumes and makeup.',
    },
    {
        title: 'Mysore Palace',
        summary: 'Historical palace and royal residence in Mysore',
        category: 'heritage-sites',
        state: 'Karnataka',
        region: 'South',
        latitude: 12.3051,
        longitude: 76.6551,
        imageUrl: 'https://i.postimg.cc/QxJqKmYy/mysore-palace.jpg',
        tags: ['palace', 'architecture', 'royal'],
        description: 'Mysore Palace is a historical palace and a royal residence. It is one of the most famous tourist attractions in India.',
    },
    {
        title: 'Pongal Festival',
        summary: 'Tamil harvest festival dedicated to the Sun God',
        category: 'festivals',
        state: 'Tamil Nadu',
        region: 'South',
        latitude: 11.1271,
        longitude: 78.6569,
        imageUrl: 'https://i.postimg.cc/nrGxJqwZ/pongal.jpg',
        tags: ['harvest', 'festival', 'tamil'],
        description: 'Pongal is a multi-day Hindu harvest festival celebrated by Tamils. It is dedicated to the Sun God and corresponds to Makar Sankranti.',
    },
    {
        title: 'Dosa',
        summary: 'Traditional South Indian fermented crepe',
        category: 'food',
        state: 'Tamil Nadu',
        region: 'South',
        latitude: 13.0827,
        longitude: 80.2707,
        imageUrl: 'https://i.postimg.cc/VkGJxHyG/dosa.jpg',
        tags: ['food', 'breakfast', 'vegetarian'],
        description: 'Dosa is a thin pancake or crepe originating from South India, made from a fermented batter predominantly consisting of lentils and rice.',
    },

    // East India
    {
        title: 'Madhubani Painting',
        summary: 'Traditional folk art from Bihar with intricate patterns',
        category: 'art',
        state: 'Bihar',
        region: 'East',
        latitude: 26.3521,
        longitude: 86.0739,
        imageUrl: 'https://i.postimg.cc/Y0qvKmYy/madhubani.jpg',
        tags: ['painting', 'folk-art', 'traditional'],
        description: 'Madhubani art is a style of Indian painting practiced in the Mithila region of Bihar. The paintings are characterized by intricate geometrical patterns.',
    },
    {
        title: 'Durga Puja',
        summary: 'Grand festival celebrating Goddess Durga in West Bengal',
        category: 'festivals',
        state: 'West Bengal',
        region: 'East',
        latitude: 22.5726,
        longitude: 88.3639,
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/durga-puja.jpg',
        tags: ['festival', 'goddess', 'celebration'],
        description: 'Durga Puja is an annual Hindu festival celebrating the goddess Durga. It is particularly popular and traditionally celebrated in West Bengal.',
    },
    {
        title: 'Konark Sun Temple',
        summary: '13th-century Sun Temple and UNESCO World Heritage Site',
        category: 'heritage-sites',
        state: 'Odisha',
        region: 'East',
        latitude: 19.8876,
        longitude: 86.0945,
        imageUrl: 'https://i.postimg.cc/QxJqKmYy/konark.jpg',
        tags: ['temple', 'unesco', 'architecture'],
        description: 'The Konark Sun Temple is a 13th-century CE sun temple at Konark about 35 km northeast of Puri. Attributed to king Narasimhadeva I of the Eastern Ganga Dynasty.',
    },

    // West India
    {
        title: 'Garba Dance',
        summary: 'Traditional folk dance from Gujarat performed during Navratri',
        category: 'music',
        state: 'Gujarat',
        region: 'West',
        latitude: 23.0225,
        longitude: 72.5714,
        imageUrl: 'https://i.postimg.cc/nrGxJqwZ/garba.jpg',
        tags: ['dance', 'folk', 'navratri'],
        description: 'Garba is a form of dance which originated in Gujarat. The name is derived from the Sanskrit term Garbha and Garba Deep. It is a traditional folk dance celebrated during Navratri.',
    },
    {
        title: 'Ajanta Caves',
        summary: 'Ancient Buddhist cave monuments with stunning murals',
        category: 'heritage-sites',
        state: 'Maharashtra',
        region: 'West',
        latitude: 20.5519,
        longitude: 75.7033,
        imageUrl: 'https://i.postimg.cc/VkGJxHyG/ajanta.jpg',
        tags: ['buddhist', 'unesco', 'caves'],
        description: 'The Ajanta Caves are approximately 30 rock-cut Buddhist cave monuments dating from the 2nd century BCE to about 480 CE in the Aurangabad district of Maharashtra.',
    },
    {
        title: 'Dhokla',
        summary: 'Savory steamed cake from Gujarat',
        category: 'food',
        state: 'Gujarat',
        region: 'West',
        latitude: 23.0225,
        longitude: 72.5714,
        imageUrl: 'https://i.postimg.cc/Y0qvKmYy/dhokla.jpg',
        tags: ['food', 'snack', 'vegetarian'],
        description: 'Dhokla is a vegetarian culinary dish that is native to the Indian state of Gujarat. It is made with a fermented batter derived from rice and split chickpeas.',
    },

    // Northeast India
    {
        title: 'Bihu Dance',
        summary: 'Folk dance from Assam performed during Bihu festival',
        category: 'music',
        state: 'Assam',
        region: 'Northeast',
        latitude: 26.2006,
        longitude: 92.9376,
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/bihu.jpg',
        tags: ['dance', 'folk', 'festival'],
        description: 'Bihu dance is an indigenous folk dance from Assam related to the Bihu festival and an important part of Assamese culture.',
    },
    {
        title: 'Hornbill Festival',
        summary: 'Festival of festivals showcasing Naga tribal culture',
        category: 'festivals',
        state: 'Nagaland',
        region: 'Northeast',
        latitude: 25.6747,
        longitude: 94.1086,
        imageUrl: 'https://i.postimg.cc/QxJqKmYy/hornbill.jpg',
        tags: ['festival', 'tribal', 'culture'],
        description: 'The Hornbill Festival is a celebration held every year from 1 to 10 December in Nagaland. It is called the "Festival of Festivals".',
    },

    // Central India
    {
        title: 'Khajuraho Temples',
        summary: 'Medieval Hindu and Jain temples famous for erotic sculptures',
        category: 'heritage-sites',
        state: 'Madhya Pradesh',
        region: 'Central',
        latitude: 24.8318,
        longitude: 79.9199,
        imageUrl: 'https://i.postimg.cc/nrGxJqwZ/khajuraho.jpg',
        tags: ['temple', 'unesco', 'sculpture'],
        description: 'The Khajuraho Group of Monuments is a group of Hindu and Jain temples in Chhatarpur district, Madhya Pradesh. They are a UNESCO World Heritage Site.',
    },
    {
        title: 'Gond Art',
        summary: 'Tribal art form from Madhya Pradesh with vibrant patterns',
        category: 'art',
        state: 'Madhya Pradesh',
        region: 'Central',
        latitude: 22.9734,
        longitude: 78.6569,
        imageUrl: 'https://i.postimg.cc/VkGJxHyG/gond-art.jpg',
        tags: ['tribal', 'painting', 'folk-art'],
        description: 'Gond painting is a form of painting from folk and tribal art that is practiced by one of the largest tribes in India – the Gond tribe.',
    },
];
