import type { Event } from './types';

/**
 * Seed data for Indian cultural events and festivals
 * Dates are for 2025-2026 cycle
 */
export const eventSeedData: Omit<Event, 'id' | 'createdAt' | 'updatedAt'>[] = [
    // National Holidays
    {
        title: 'Republic Day',
        summary: 'Celebrate the adoption of the Indian Constitution with grand parades and cultural programs.',
        description: 'Republic Day marks the date when the Constitution of India came into effect on 26 January 1950. The main Republic Day celebration is held in New Delhi at Rajpath with a grand parade showcasing India\'s defense capability, cultural and social heritage.',
        category: 'cultural',
        state: 'Delhi',
        city: 'New Delhi',
        region: 'North India',
        latitude: 28.6139,
        longitude: 77.2090,
        startDate: new Date('2025-01-26T09:00:00'),
        endDate: new Date('2025-01-26T18:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Republic Day parade India Gate',
        tags: ['national', 'parade', 'patriotic', 'cultural'],
        significance: 'Commemorates the adoption of the Constitution of India',
        featured: true,
        priority: 1,
    },
    {
        title: 'Independence Day',
        summary: 'Commemorate India\'s freedom from British rule with flag hoisting and patriotic celebrations.',
        description: 'Independence Day is celebrated annually on 15 August as a national holiday to commemorate the nation\'s independence from the British Empire. The Prime Minister hoists the national flag at the Red Fort in Delhi and delivers an address to the nation.',
        category: 'cultural',
        state: 'Delhi',
        city: 'New Delhi',
        region: 'North India',
        latitude: 28.6562,
        longitude: 77.2410,
        startDate: new Date('2025-08-15T07:00:00'),
        endDate: new Date('2025-08-15T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Independence Day Red Fort tricolor',
        tags: ['national', 'independence', 'patriotic', 'flag'],
        significance: 'Marks India\'s independence from British colonial rule in 1947',
        featured: true,
        priority: 2,
    },
    {
        title: 'Gandhi Jayanti',
        summary: 'Honor Mahatma Gandhi\'s birthday with tributes and remembrance of his teachings.',
        description: 'Gandhi Jayanti is celebrated on 2 October to mark the birth anniversary of Mahatma Gandhi. It is one of the three national holidays of India and is observed with prayer services and tributes all across India.',
        category: 'cultural',
        state: 'Delhi',
        city: 'New Delhi',
        region: 'North India',
        latitude: 28.6139,
        longitude: 77.2090,
        startDate: new Date('2025-10-02T06:00:00'),
        endDate: new Date('2025-10-02T18:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Gandhi statue prayer ceremony',
        tags: ['national', 'gandhi', 'peace', 'non-violence'],
        significance: 'Birth anniversary of Mahatma Gandhi, Father of the Nation',
        featured: false,
    },

    // Major Festivals
    {
        title: 'Holi',
        summary: 'The festival of colors celebrating the victory of good over evil with vibrant color play.',
        description: 'Holi is the Hindu festival of colors and spring, celebrated with great enthusiasm across India. People play with colored powders and water, enjoy festive foods, and celebrate the victory of good over evil.',
        category: 'festivals',
        state: 'Uttar Pradesh',
        city: 'Mathura',
        region: 'North India',
        latitude: 27.4924,
        longitude: 77.6737,
        startDate: new Date('2025-03-14T06:00:00'),
        endDate: new Date('2025-03-14T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Holi colors celebration people',
        tags: ['festival', 'colors', 'spring', 'hindu'],
        significance: 'Celebrates the victory of good over evil and the arrival of spring',
        featured: true,
        priority: 3,
    },
    {
        title: 'Diwali',
        summary: 'Festival of lights celebrating the victory of light over darkness with lamps and fireworks.',
        description: 'Diwali, the festival of lights, is one of the most popular Hindu festivals. Celebrated over five days, it symbolizes the spiritual victory of light over darkness, good over evil. Homes are decorated with oil lamps, rangoli, and lights.',
        category: 'festivals',
        state: 'Uttar Pradesh',
        city: 'Ayodhya',
        region: 'North India',
        latitude: 26.7922,
        longitude: 82.1998,
        startDate: new Date('2025-10-20T06:00:00'),
        endDate: new Date('2025-10-24T23:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Diwali diyas lights celebration',
        tags: ['festival', 'lights', 'diwali', 'hindu', 'fireworks'],
        significance: 'Celebrates Lord Rama\'s return to Ayodhya after 14 years of exile',
        featured: true,
        priority: 4,
    },
    {
        title: 'Durga Puja',
        summary: 'Grand celebration of Goddess Durga with elaborate pandals and cultural performances.',
        description: 'Durga Puja is an annual Hindu festival celebrating the worship of Goddess Durga. Particularly popular in West Bengal, it features elaborate pandals (temporary structures), artistic idols, cultural programs, and traditional rituals over ten days.',
        category: 'festivals',
        state: 'West Bengal',
        city: 'Kolkata',
        region: 'East India',
        latitude: 22.5726,
        longitude: 88.3639,
        startDate: new Date('2025-09-30T06:00:00'),
        endDate: new Date('2025-10-04T22:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Durga Puja pandal goddess idol',
        tags: ['festival', 'durga', 'bengali', 'hindu', 'pandal'],
        significance: 'Celebrates the victory of Goddess Durga over the demon Mahishasura',
        featured: true,
        priority: 5,
    },
    {
        title: 'Ganesh Chaturthi',
        summary: 'Celebrate Lord Ganesha\'s birthday with grand processions and idol immersions.',
        description: 'Ganesh Chaturthi is a Hindu festival celebrating the birth of Lord Ganesha. The festival is marked by the installation of Ganesha idols in homes and public pandals, followed by immersion ceremonies after 10 days.',
        category: 'festivals',
        state: 'Maharashtra',
        city: 'Mumbai',
        region: 'West India',
        latitude: 19.0760,
        longitude: 72.8777,
        startDate: new Date('2025-08-27T06:00:00'),
        endDate: new Date('2025-09-05T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Ganesh Chaturthi idol procession',
        tags: ['festival', 'ganesha', 'hindu', 'maharashtra', 'visarjan'],
        significance: 'Celebrates the birth of Lord Ganesha, the remover of obstacles',
        featured: true,
        priority: 6,
    },

    // Regional Festivals
    {
        title: 'Pongal',
        summary: 'Tamil harvest festival thanking the Sun God with traditional cooking and celebrations.',
        description: 'Pongal is a four-day harvest festival celebrated in Tamil Nadu. It is dedicated to the Sun God and marks the end of the winter solstice. The festival is named after the ceremonial dish Pongal, made from freshly harvested rice.',
        category: 'festivals',
        state: 'Tamil Nadu',
        city: 'Chennai',
        region: 'South India',
        latitude: 13.0827,
        longitude: 80.2707,
        startDate: new Date('2025-01-14T06:00:00'),
        endDate: new Date('2025-01-17T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Pongal pot cooking harvest',
        tags: ['festival', 'harvest', 'tamil', 'pongal', 'sun'],
        significance: 'Harvest festival thanking the Sun God for agricultural prosperity',
        featured: false,
    },
    {
        title: 'Onam',
        summary: 'Kerala\'s harvest festival with flower carpets, boat races, and traditional feasts.',
        description: 'Onam is the annual harvest festival of Kerala. The festival is marked by Vallam Kali (boat races), Puli Kali (tiger dances), Pookalam (flower arrangements), Onathappan (worship), Onam Kali, Tug of War, and the grand Onam Sadya feast.',
        category: 'festivals',
        state: 'Kerala',
        city: 'Kochi',
        region: 'South India',
        latitude: 9.9312,
        longitude: 76.2673,
        startDate: new Date('2025-08-25T06:00:00'),
        endDate: new Date('2025-09-05T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Onam pookalam flower carpet',
        tags: ['festival', 'harvest', 'kerala', 'onam', 'boat-race'],
        significance: 'Celebrates the homecoming of King Mahabali',
        featured: false,
    },
    {
        title: 'Bihu',
        summary: 'Assamese New Year celebration with traditional dance, music, and feasting.',
        description: 'Bihu is a set of three important Assamese festivals. Rongali Bihu (April) celebrates the Assamese New Year and spring harvest. The festival is marked by traditional Bihu dance, music, and community feasts.',
        category: 'festivals',
        state: 'Assam',
        city: 'Guwahati',
        region: 'Northeast India',
        latitude: 26.1445,
        longitude: 91.7362,
        startDate: new Date('2025-04-14T06:00:00'),
        endDate: new Date('2025-04-20T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Bihu dance traditional Assam',
        tags: ['festival', 'new-year', 'assam', 'bihu', 'dance'],
        significance: 'Assamese New Year and spring harvest festival',
        featured: false,
    },
    {
        title: 'Theyyam',
        summary: 'Ancient ritualistic performance art from Kerala with elaborate costumes and divine possession.',
        description: 'Theyyam is a popular ritual form of worship in Kerala and Karnataka. It is a rare combination of dance, music, and fervent devotion. Performers wear elaborate costumes and enact the deity through trance-like states.',
        category: 'rituals',
        state: 'Kerala',
        city: 'Kannur',
        region: 'South India',
        latitude: 11.8745,
        longitude: 75.3704,
        startDate: new Date('2025-04-07T18:00:00'),
        endDate: new Date('2025-04-14T23:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Theyyam ritual dark costume',
        tags: ['ritual', 'kerala', 'theyyam', 'dance', 'worship'],
        significance: 'Ancient ritualistic worship combining dance, music, and devotion',
        featured: true,
        priority: 7,
    },

    // Cultural Events & Fairs
    {
        title: 'Pushkar Camel Fair',
        summary: 'World\'s largest camel fair with livestock trading, cultural events, and competitions.',
        description: 'The Pushkar Camel Fair is an annual multi-day livestock fair and cultural event held in Pushkar, Rajasthan. It is one of the world\'s largest camel fairs, attracting thousands of camels, horses, and cattle traders along with tourists.',
        category: 'cultural',
        state: 'Rajasthan',
        city: 'Pushkar',
        region: 'North India',
        latitude: 26.4899,
        longitude: 74.5511,
        startDate: new Date('2025-11-04T06:00:00'),
        endDate: new Date('2025-11-12T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Pushkar camel fair Rajasthan',
        tags: ['fair', 'camel', 'rajasthan', 'pushkar', 'livestock'],
        significance: 'World\'s largest camel fair and cultural extravaganza',
        featured: true,
        priority: 8,
    },
    {
        title: 'Hornbill Festival',
        summary: 'Festival of festivals showcasing Nagaland\'s tribal culture, music, and traditions.',
        description: 'The Hornbill Festival is held annually in Nagaland to encourage inter-tribal interaction and promote cultural heritage. It showcases traditional arts, dances, songs, games, and food of all the tribes of Nagaland.',
        category: 'cultural',
        state: 'Nagaland',
        city: 'Kohima',
        region: 'Northeast India',
        latitude: 25.6747,
        longitude: 94.1078,
        startDate: new Date('2025-12-01T09:00:00'),
        endDate: new Date('2025-12-10T18:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Hornbill festival Nagaland tribal',
        tags: ['festival', 'tribal', 'nagaland', 'hornbill', 'culture'],
        significance: 'Celebrates the rich cultural heritage of Nagaland tribes',
        featured: true,
        priority: 9,
    },
    {
        title: 'Jaipur Literature Festival',
        summary: 'Asia\'s largest literary festival featuring renowned authors, poets, and thinkers.',
        description: 'The Jaipur Literature Festival is an annual literary festival which takes place in Jaipur, Rajasthan. It is the world\'s largest free literary festival, featuring writers, thinkers, and literary enthusiasts from around the globe.',
        category: 'cultural',
        state: 'Rajasthan',
        city: 'Jaipur',
        region: 'North India',
        latitude: 26.9124,
        longitude: 75.7873,
        startDate: new Date('2025-01-23T09:00:00'),
        endDate: new Date('2025-01-27T19:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Jaipur Literature Festival books',
        tags: ['literature', 'festival', 'jaipur', 'books', 'authors'],
        significance: 'World\'s largest free literary festival',
        featured: false,
    },
    {
        title: 'Surajkund Mela',
        summary: 'International crafts fair showcasing traditional handicrafts and folk culture.',
        description: 'The Surajkund International Crafts Mela is an annual fair held in Faridabad near Delhi. It showcases traditional handicrafts, handlooms, and cultural heritage from across India and partner nations.',
        category: 'cultural',
        state: 'Haryana',
        city: 'Faridabad',
        region: 'North India',
        latitude: 28.4089,
        longitude: 77.3178,
        startDate: new Date('2025-02-01T10:00:00'),
        endDate: new Date('2025-02-17T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Surajkund mela handicrafts fair',
        tags: ['fair', 'handicrafts', 'culture', 'mela', 'traditional'],
        significance: 'Largest crafts fair in India showcasing traditional artisans',
        featured: false,
    },

    // Music & Dance Festivals
    {
        title: 'Khajuraho Dance Festival',
        summary: 'Classical dance festival against the backdrop of ancient temple sculptures.',
        description: 'The Khajuraho Dance Festival is a week-long festival of classical dances held annually against the backdrop of the Khajuraho temples. It features performances by renowned classical dancers from across India.',
        category: 'dance',
        state: 'Madhya Pradesh',
        city: 'Khajuraho',
        region: 'Central India',
        latitude: 24.8318,
        longitude: 79.9199,
        startDate: new Date('2025-02-20T18:00:00'),
        endDate: new Date('2025-02-26T22:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Khajuraho dance classical temple',
        tags: ['dance', 'classical', 'khajuraho', 'temple', 'festival'],
        significance: 'Celebrates classical Indian dance forms at UNESCO World Heritage site',
        featured: false,
    },
    {
        title: 'Konark Dance Festival',
        summary: 'Classical dance festival at the Sun Temple showcasing Odissi and other forms.',
        description: 'The Konark Dance Festival is held annually in the backdrop of the Sun Temple in Konark, Odisha. It features classical dance performances, particularly Odissi, by renowned artists from across India.',
        category: 'dance',
        state: 'Odisha',
        city: 'Konark',
        region: 'East India',
        latitude: 19.8876,
        longitude: 86.0945,
        startDate: new Date('2025-12-01T18:00:00'),
        endDate: new Date('2025-12-05T22:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Konark dance Odissi sun temple',
        tags: ['dance', 'odissi', 'konark', 'classical', 'temple'],
        significance: 'Celebrates classical dance at the iconic Sun Temple',
        featured: false,
    },

    // Food Festivals
    {
        title: 'Goa Food and Cultural Festival',
        summary: 'Celebrate Goan cuisine and culture with food stalls, music, and performances.',
        description: 'The Goa Food and Cultural Festival showcases the rich culinary heritage of Goa along with traditional music, dance, and cultural performances. It features authentic Goan dishes, seafood, and local delicacies.',
        category: 'food',
        state: 'Goa',
        city: 'Panaji',
        region: 'West India',
        latitude: 15.4909,
        longitude: 73.8278,
        startDate: new Date('2025-11-15T10:00:00'),
        endDate: new Date('2025-11-23T22:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Goan food festival seafood',
        tags: ['food', 'goa', 'cuisine', 'seafood', 'festival'],
        significance: 'Celebrates the unique Indo-Portuguese culinary heritage of Goa',
        featured: false,
    },

    // Heritage Events
    {
        title: 'Hampi Utsav',
        summary: 'Cultural extravaganza celebrating the heritage of the Vijayanagara Empire.',
        description: 'Hampi Utsav is an annual cultural festival held in the ruins of Hampi, a UNESCO World Heritage Site. The festival features classical music and dance performances, puppet shows, fireworks, and a grand procession.',
        category: 'heritage',
        state: 'Karnataka',
        city: 'Hampi',
        region: 'South India',
        latitude: 15.3350,
        longitude: 76.4600,
        startDate: new Date('2025-11-07T17:00:00'),
        endDate: new Date('2025-11-09T23:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Hampi ruins heritage festival',
        tags: ['heritage', 'hampi', 'vijayanagara', 'unesco', 'festival'],
        significance: 'Celebrates the glorious past of the Vijayanagara Empire',
        featured: false,
    },
    {
        title: 'Taj Mahotsav',
        summary: 'Cultural festival celebrating Agra\'s art, crafts, and culinary heritage.',
        description: 'Taj Mahotsav is an annual 10-day event held in Agra celebrating the rich cultural heritage of the region. It features traditional crafts, music, dance, cuisine, and showcases artisans from across India.',
        category: 'heritage',
        state: 'Uttar Pradesh',
        city: 'Agra',
        region: 'North India',
        latitude: 27.1767,
        longitude: 78.0081,
        startDate: new Date('2025-02-18T10:00:00'),
        endDate: new Date('2025-02-27T22:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Taj Mahal festival crafts',
        tags: ['heritage', 'taj-mahal', 'agra', 'crafts', 'festival'],
        significance: 'Celebrates the cultural heritage of the Mughal era',
        featured: false,
    },

    // Additional Festivals
    {
        title: 'Navratri',
        summary: 'Nine nights of worship, dance, and celebration honoring Goddess Durga.',
        description: 'Navratri is a Hindu festival that spans nine nights and is celebrated across India. In Gujarat, it is famous for Garba and Dandiya Raas dances. The festival honors Goddess Durga and her nine forms.',
        category: 'festivals',
        state: 'Gujarat',
        city: 'Ahmedabad',
        region: 'West India',
        latitude: 23.0225,
        longitude: 72.5714,
        startDate: new Date('2025-09-22T18:00:00'),
        endDate: new Date('2025-09-30T23:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Navratri garba dance Gujarat',
        tags: ['festival', 'navratri', 'garba', 'dandiya', 'gujarat'],
        significance: 'Nine nights of worship honoring the divine feminine',
        featured: false,
    },
    {
        title: 'Rath Yatra',
        summary: 'Grand chariot procession of Lord Jagannath in Puri.',
        description: 'Rath Yatra is a famous Hindu festival associated with Lord Jagannath held at Puri, Odisha. The festival involves a public procession with three chariots carrying the deities Jagannath, Balabhadra, and Subhadra.',
        category: 'festivals',
        state: 'Odisha',
        city: 'Puri',
        region: 'East India',
        latitude: 19.8135,
        longitude: 85.8312,
        startDate: new Date('2025-06-29T06:00:00'),
        endDate: new Date('2025-07-07T20:00:00'),
        imageUrl: 'https://i.postimg.cc/pLhBc0Gy/theyyam.jpg',
        imageHint: 'Rath Yatra chariot Puri',
        tags: ['festival', 'rath-yatra', 'jagannath', 'puri', 'chariot'],
        significance: 'Annual chariot procession of Lord Jagannath',
        featured: false,
    },
];
